name: Generate JaCoCo Badge
on:
  push:
    branches:
      - main
      - master
      - staging
      - dev
  pull_request:
    branches:
      - main
      - master
      - staging
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Install gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle
      - name: Run Tests
        run: ./gradlew test
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/customJacocoReportDir/test/jacocoTestReport.csv
      - name: Update Jacoco Badge
        uses: test-room-7/action-update-file@v1
        with:
          file-path: .github/badges/jacoco.svg
          commit-msg: Update Jacoco Badge
          github-token: ${{ secrets.GITHUB_TOKEN }}
